<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns="http://j2ee.netbeans.org/wsdl/Processes/src/WSDLServiceWrapper" xmlns:ns1="http://j2ee.netbeans.org/wsdl/Processes/src/RESTServiceWrapper2" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:ns2="http://j2ee.netbeans.org/wsdl/Processes/src/WADLServiceWrapper">
    <import namespace="http://j2ee.netbeans.org/wsdl/Processes/src/WSDLServiceWrapper" location="WSDLServiceWrapper.wsdl"/>
    <import namespace="http://j2ee.netbeans.org/wsdl/Processes/src/RESTServiceWrapper2" location="RESTServiceWrapper.wsdl"/>
    <import namespace="http://j2ee.netbeans.org/wsdl/Processes/src/WADLServiceWrapper" location="WADLServiceWrapper.wsdl"/>
    <vprop:property name="wzrd_prop_int_int" type="xsd:int"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns:AnalyzeRequestWSDL" part="id"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns:AnalyzeResponseWSDL" part="id"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns1:AnalyzeRequestREST" part="id"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns1:AnalyzeResponseREST" part="id"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns2:AnalyzeRequestWADL" part="id"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_int_int" messageType="ns2:AnalyzeResponseWADL" part="id"/>
</definitions>
